from .config import (
    DEFAULT_ASYNC_LIMIT,
    DEFAULT_HOST_WORKERS,
    DEFAULT_HOST_GROUP_SIZE,
    DEFAULT_HOST_TIMEOUT,
    DEFAULT_PLUGIN_WORKERS,
    DEFAULT_PORTS,
    DEFAULT_SERVICE_INTENSITY,
    DEFAULT_STATS_EVERY,
    DEFAULT_TIMING_TEMPLATE,
    MAX_RTT_TIMEOUT,
    MIN_RTT_TIMEOUT,
    TOP_COMMON_PORTS,
)

PROFILE_CHOICES = ("quick", "stealth", "aggressive", "web", "vuln", "root")

_QUICK_PORTS = ",".join(str(port) for port in TOP_COMMON_PORTS[:30])
_WEB_PORTS = "80,81,443,444,591,8000,8008,8080,8081,8088,8443,8888"

PROFILES = {
    "quick": {
        "name": "quick",
        "description": "Fast top-ports scan for rapid visibility.",
        "ports": _QUICK_PORTS,
        "stealth": False,
        "syn": False,
        "services": True,
        "plugins": False,
        "cve_lookup": False,
        "threads": 120,
        "host_workers": 16,
        "plugin_workers": 6,
        "async_limit": 16,
        "host_group_size": 20,
        "timeout": 1.0,
        "retries": 1,
        "rate_limit": 0.0,
        "timing_template": 4,
        "service_intensity": DEFAULT_SERVICE_INTENSITY,
        "host_timeout": DEFAULT_HOST_TIMEOUT,
        "stats_every": DEFAULT_STATS_EVERY,
        "min_rtt_timeout": MIN_RTT_TIMEOUT,
        "max_rtt_timeout": MAX_RTT_TIMEOUT,
        "randomize": False,
        "host_discovery": True,
        "root_scan": False,
        "auto_elevate": False,
    },
    "stealth": {
        "name": "stealth",
        "description": "Lower-noise scan with randomized order and pacing.",
        "ports": DEFAULT_PORTS,
        "stealth": True,
        "syn": True,
        "services": False,
        "plugins": False,
        "cve_lookup": False,
        "threads": 80,
        "host_workers": 10,
        "plugin_workers": 4,
        "async_limit": 10,
        "host_group_size": 12,
        "timeout": 1.4,
        "retries": 1,
        "rate_limit": 0.03,
        "timing_template": 2,
        "service_intensity": 2,
        "host_timeout": DEFAULT_HOST_TIMEOUT,
        "stats_every": DEFAULT_STATS_EVERY,
        "min_rtt_timeout": MIN_RTT_TIMEOUT,
        "max_rtt_timeout": MAX_RTT_TIMEOUT,
        "randomize": True,
        "host_discovery": True,
        "root_scan": False,
        "auto_elevate": False,
    },
    "aggressive": {
        "name": "aggressive",
        "description": "Deep recon with service checks and plugin modules.",
        "ports": DEFAULT_PORTS,
        "stealth": False,
        "syn": False,
        "services": True,
        "plugins": True,
        "cve_lookup": True,
        "threads": 220,
        "host_workers": DEFAULT_HOST_WORKERS,
        "plugin_workers": DEFAULT_PLUGIN_WORKERS,
        "async_limit": DEFAULT_ASYNC_LIMIT,
        "host_group_size": DEFAULT_HOST_GROUP_SIZE,
        "timeout": 1.0,
        "retries": 2,
        "rate_limit": 0.0,
        "timing_template": 4,
        "service_intensity": 8,
        "host_timeout": DEFAULT_HOST_TIMEOUT,
        "stats_every": DEFAULT_STATS_EVERY,
        "min_rtt_timeout": MIN_RTT_TIMEOUT,
        "max_rtt_timeout": MAX_RTT_TIMEOUT,
        "randomize": True,
        "host_discovery": True,
        "root_scan": False,
        "auto_elevate": False,
    },
    "web": {
        "name": "web",
        "description": "HTTP/TLS focused scan with security header checks.",
        "ports": _WEB_PORTS,
        "stealth": False,
        "syn": False,
        "services": True,
        "plugins": True,
        "cve_lookup": True,
        "threads": 160,
        "host_workers": 20,
        "plugin_workers": DEFAULT_PLUGIN_WORKERS,
        "async_limit": DEFAULT_ASYNC_LIMIT,
        "host_group_size": 24,
        "timeout": 1.5,
        "retries": 1,
        "rate_limit": 0.01,
        "timing_template": 4,
        "service_intensity": 7,
        "host_timeout": DEFAULT_HOST_TIMEOUT,
        "stats_every": DEFAULT_STATS_EVERY,
        "min_rtt_timeout": MIN_RTT_TIMEOUT,
        "max_rtt_timeout": MAX_RTT_TIMEOUT,
        "randomize": True,
        "host_discovery": True,
        "root_scan": False,
        "auto_elevate": False,
    },
    "vuln": {
        "name": "vuln",
        "description": "Service and vulnerability-oriented assessment profile.",
        "ports": DEFAULT_PORTS,
        "stealth": False,
        "syn": False,
        "services": True,
        "plugins": True,
        "cve_lookup": True,
        "threads": 180,
        "host_workers": DEFAULT_HOST_WORKERS,
        "plugin_workers": DEFAULT_PLUGIN_WORKERS,
        "async_limit": DEFAULT_ASYNC_LIMIT,
        "host_group_size": DEFAULT_HOST_GROUP_SIZE,
        "timeout": 1.3,
        "retries": 2,
        "rate_limit": 0.005,
        "timing_template": DEFAULT_TIMING_TEMPLATE,
        "service_intensity": 8,
        "host_timeout": DEFAULT_HOST_TIMEOUT,
        "stats_every": DEFAULT_STATS_EVERY,
        "min_rtt_timeout": MIN_RTT_TIMEOUT,
        "max_rtt_timeout": MAX_RTT_TIMEOUT,
        "randomize": True,
        "host_discovery": True,
        "root_scan": False,
        "auto_elevate": False,
    },
    "root": {
        "name": "root",
        "description": "Privileged raw scan mode (requires root/admin).",
        "ports": DEFAULT_PORTS,
        "stealth": False,
        "syn": True,
        "services": True,
        "plugins": True,
        "cve_lookup": True,
        "threads": 160,
        "host_workers": DEFAULT_HOST_WORKERS,
        "plugin_workers": DEFAULT_PLUGIN_WORKERS,
        "async_limit": DEFAULT_ASYNC_LIMIT,
        "host_group_size": DEFAULT_HOST_GROUP_SIZE,
        "timeout": 1.0,
        "retries": 2,
        "rate_limit": 0.0,
        "timing_template": 3,
        "service_intensity": 9,
        "host_timeout": DEFAULT_HOST_TIMEOUT,
        "stats_every": DEFAULT_STATS_EVERY,
        "min_rtt_timeout": MIN_RTT_TIMEOUT,
        "max_rtt_timeout": MAX_RTT_TIMEOUT,
        "randomize": True,
        "host_discovery": True,
        "root_scan": True,
        "auto_elevate": True,
    },
}


def resolve_profile(profile_name):
    key = (profile_name or "quick").strip().lower()
    if key not in PROFILES:
        supported = ", ".join(PROFILE_CHOICES)
        raise ValueError(f"Unsupported profile '{profile_name}'. Supported: {supported}")
    return dict(PROFILES[key])
